name: Build and Deploy Cal.com

on:
  push:
    branches: [main, dev]
    paths:
      - '**'
      - '.github/workflows/calcom-deploy.yml'
      - '!.github/**'
      - '!docs/**'
      - '!*.md'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: kwt-dev/calcom

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=dev-latest,enable=${{ github.ref == 'refs/heads/dev' }}
            type=sha,prefix={{branch}}-
            type=raw,value=coolify,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          no-cache: true
          build-args: |
            NEXT_PUBLIC_WEBAPP_URL=https://cal.kingswindowtint.com
            NEXT_PUBLIC_API_V2_URL=https://cal.kingswindowtint.com/api/v2
            NEXT_PUBLIC_LICENSE_CONSENT=agree
            CALCOM_TELEMETRY_DISABLED=1
            NEXT_PUBLIC_IS_E2E=
            DATABASE_URL=postgresql://postgres:placeholder@postgres:5432/calcom
            NEXTAUTH_SECRET=placeholder_secret_for_build
            CALENDSO_ENCRYPTION_KEY=placeholder_key_for_build
            NEXT_PUBLIC_WEBSITE_URL=https://cal.kingswindowtint.com
            NEXT_PUBLIC_CONSOLE_URL=https://cal.kingswindowtint.com
            NEXT_PUBLIC_EMBED_LIB_URL=https://cal.kingswindowtint.com/embed/embed.js
            NEXT_PUBLIC_COMPANY_NAME=Kings Window Tint
            NEXT_PUBLIC_APP_NAME=Cal
            NEXT_PUBLIC_SUPPORT_MAIL_ADDRESS=support@kingswindowtint.com
            NEXT_PUBLIC_DISABLE_SIGNUP=false

      - name: Deployment complete
        run: |
          echo "## 🚀 Cal.com Deployment Complete" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Cal.com Image:** \`${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest\`" >> $GITHUB_STEP_SUMMARY
          echo "**Commit:** \`${{ github.sha }}\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Coolify Setup Instructions:" >> $GITHUB_STEP_SUMMARY
          echo "1. Update docker-compose.yml to use image: \`${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest\`" >> $GITHUB_STEP_SUMMARY
          echo "2. Ensure port: 3000 is exposed" >> $GITHUB_STEP_SUMMARY
          echo "3. Configure health check: /auth/login on port 3000" >> $GITHUB_STEP_SUMMARY
          echo "4. Set all required environment variables (NEXTAUTH_SECRET, DATABASE_URL, etc.)" >> $GITHUB_STEP_SUMMARY